# /app/schemas/one_on_one_session.py
from pydantic import BaseModel
from uuid import UUID
from datetime import datetime
from enum import Enum
from typing import List, Optional
# CREATE TYPE session_status AS ENUM (
#   'requested',
#   'approved',
#   'rejected',
#   'live',
#   'ended'
# );
class SessionLifecycle(str, Enum):
    requested = 'requested'
    approved = 'approved'
    rejected = 'rejected'
    live='live'
    ended ='ended'


class PreDirectSessionRequest(BaseModel): #handles one_on_one_session request
    start_time : datetime
    end_time : datetime

class PreDirectSessionResponse(PreDirectSessionRequest): #handles one_on_one_session response
    customer_id : UUID
    status : SessionLifecycle

class DirectSessionResponse(BaseModel):
    # id generated by supabase
    stream_id : UUID
    priest_id : UUID
    customer_id: UUID
    start_time: datetime
    end_time : datetime
    status: SessionLifecycle

class DirectSessionListResponse(BaseModel):
    items: List[DirectSessionResponse]

class DirectSessionUpdate(BaseModel):
    # id generated by supabase
    stream_id : Optional[UUID] = None
    priest_id : UUID
    customer_id: UUID
    start_time: datetime
    end_time : datetime
    status: SessionLifecycle
